#!/usr/bin/env node
/**
 * TeamOS detach script — removes teamos-created artifacts from a host project
 * without touching the team/ workspace data (members, projects, etc.).
 *
 * Usage:
 *   node teamos/scripts/detach.mjs              # from project root
 *   node teamos/scripts/detach.mjs --project /path/to/project
 *
 * What it removes:
 *   - team/AGENTS.md and team/CLAUDE.md (if teamos-created)
 *   - The <!-- teamos --> section from root AGENTS.md
 *   - In symlink mode: the teamos symlink and .gitignore entries
 *   - In submodule mode: prints git commands (doesn't execute them)
 *
 * What it never touches:
 *   - team/ directory and its workspace data (members, org.md, etc.)
 *   - Any file not created by teamos init
 */

import { readFile, writeFile, unlink, lstat, readlink, access } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { constants } from 'node:fs';

// ─── Configuration ─────────────────────────────────────────────────────────────

const AGENT_RULE_NAMES = ['AGENTS.md', 'CLAUDE.md'];

const TEAMOS_STUB_MARKER = '<!-- Generated by teamos init';
const TEAMOS_SECTION_MARKER = '<!-- teamos -->';

// ─── Helpers ───────────────────────────────────────────────────────────────────

function log(msg) { console.log(`  ${msg}`); }
function warn(msg) { console.warn(`  ! ${msg}`); }

async function exists(path) {
	try { await access(path, constants.F_OK); return true; } catch { return false; }
}

async function isSymlink(path) {
	try { const s = await lstat(path); return s.isSymbolicLink(); } catch { return false; }
}

async function isFile(path) {
	try { const s = await lstat(path); return s.isFile(); } catch { return false; }
}

async function readTextOrEmpty(path) {
	try { return await readFile(path, 'utf-8'); } catch { return ''; }
}

// ─── Detach steps ──────────────────────────────────────────────────────────────

async function removeTeamRuleFiles(projectRoot) {
	const teamDir = join(projectRoot, 'team');

	for (const name of AGENT_RULE_NAMES) {
		const filePath = join(teamDir, name);

		if (!await exists(filePath)) continue;

		if (await isSymlink(filePath)) {
			const target = await readlink(filePath);
			if (target.includes('teamos')) {
				await unlink(filePath);
				log(`Removed symlink: team/${name}`);
			} else {
				warn(`team/${name} is a symlink but doesn't point to teamos — skipping`);
			}
			continue;
		}

		const content = await readTextOrEmpty(filePath);
		if (content.includes(TEAMOS_STUB_MARKER)) {
			await unlink(filePath);
			log(`Removed stub: team/${name}`);
		} else {
			warn(`team/${name} doesn't appear to be teamos-created — skipping`);
		}
	}
}

async function removeTeamosSectionFromRootFiles(projectRoot) {
	for (const name of AGENT_RULE_NAMES) {
		const filePath = join(projectRoot, name);
		const content = await readTextOrEmpty(filePath);

		if (!content || !content.includes(TEAMOS_SECTION_MARKER)) continue;

		const markerIdx = content.indexOf(TEAMOS_SECTION_MARKER);

		// Find start of teamos section — include blank lines before marker
		let sectionStart = markerIdx;
		while (sectionStart > 0 && content[sectionStart - 1] === '\n') {
			sectionStart--;
		}

		// Section runs from marker to next <!-- marker or end of file
		const afterMarker = content.indexOf('\n<!--', markerIdx + TEAMOS_SECTION_MARKER.length);
		const sectionEnd = afterMarker !== -1 ? afterMarker : content.length;

		const before = content.slice(0, sectionStart);
		const after = content.slice(sectionEnd);
		const result = (before + after).trim();

		if (result.length === 0) {
			await unlink(filePath);
			log(`Removed ${name} (was teamos-only content)`);
		} else {
			await writeFile(filePath, result + '\n', 'utf-8');
			log(`Removed teamos section from ${name}`);
		}
	}
}

async function handleSymlinkMode(projectRoot) {
	const teamosLink = join(projectRoot, 'teamos');

	if (await isSymlink(teamosLink)) {
		await unlink(teamosLink);
		log('Removed teamos symlink');
	}

	// Clean .gitignore entries
	const gitignorePath = join(projectRoot, '.gitignore');
	const content = await readTextOrEmpty(gitignorePath);
	if (!content) return;

	const teamosEntries = new Set(['teamos', ...AGENT_RULE_NAMES.map(n => `team/${n}`)]);
	const lines = content.split('\n');
	const filtered = lines.filter(line => !teamosEntries.has(line.trim()));

	if (filtered.length !== lines.length) {
		const result = filtered.join('\n').replace(/\n{3,}/g, '\n\n').trim();
		if (result.length === 0) {
			await unlink(gitignorePath);
			log('Removed .gitignore (was teamos-only content)');
		} else {
			await writeFile(gitignorePath, result + '\n', 'utf-8');
			log('Cleaned teamos entries from .gitignore');
		}
	}
}

async function handleSubmoduleMode() {
	console.log('\n  To remove the teamos submodule, run:\n');
	console.log('    git submodule deinit -f teamos');
	console.log('    git rm teamos');
	console.log('    rm -rf .git/modules/teamos');
	console.log('    git commit -m "remove teamos"\n');
}

// ─── Detection ─────────────────────────────────────────────────────────────────

async function detectMode(projectRoot) {
	const teamosInProject = join(projectRoot, 'teamos');

	if (await isSymlink(teamosInProject)) return 'symlink';

	if (await exists(teamosInProject)) {
		const dotGitPath = join(teamosInProject, '.git');
		if (await isFile(dotGitPath)) {
			const content = await readTextOrEmpty(dotGitPath);
			if (content.includes('gitdir:')) return 'submodule';
		}
	}

	return 'unknown';
}

// ─── CLI ───────────────────────────────────────────────────────────────────────

function parseArgs(argv) {
	const opts = { projectRoot: process.cwd() };
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--project' && argv[i + 1]) {
			opts.projectRoot = resolve(argv[++i]);
		} else if (argv[i] === '--help') {
			console.log([
				'TeamOS detach — remove teamos artifacts from a project',
				'',
				'Usage:',
				'  node teamos/scripts/detach.mjs',
				'  node teamos/scripts/detach.mjs --project /path/to/project',
				'',
				'Removes teamos-created files. Never deletes team/ workspace data.',
			].join('\n'));
			process.exit(0);
		}
	}
	return opts;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
	const opts = parseArgs(process.argv.slice(2));
	const projectRoot = opts.projectRoot;
	const mode = await detectMode(projectRoot);

	console.log(`\nTeamOS detach — project: ${projectRoot}`);
	console.log(`                mode:    ${mode}\n`);

	// Step 1: Remove team/AGENTS.md and team/CLAUDE.md
	await removeTeamRuleFiles(projectRoot);

	// Step 2: Remove teamos section from root convention files
	await removeTeamosSectionFromRootFiles(projectRoot);

	// Step 3: Mode-specific cleanup
	if (mode === 'symlink') {
		await handleSymlinkMode(projectRoot);
	} else if (mode === 'submodule') {
		await handleSubmoduleMode();
	}

	console.log('Done.\n');
}

main().catch((err) => {
	console.error('TeamOS detach failed:', err);
	process.exit(1);
});
