#!/usr/bin/env node
/**
 * TeamOS project initialization script.
 *
 * Detects how teamos is installed (git submodule, git subtree, or symlink)
 * and sets up the team/ workspace scaffold and agent-rules references in
 * the host project.
 *
 * Usage:
 *   node teamos/scripts/init.mjs              # from project root (submodule/subtree mode)
 *   node /path/to/teamos/scripts/init.mjs     # from project root (symlink mode)
 *   node teamos/scripts/init.mjs --project /path/to/project
 *
 * Idempotent and non-destructive — safe to re-run at any time.
 */

import { readFile, writeFile, mkdir, symlink, lstat, access } from 'node:fs/promises';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { constants } from 'node:fs';
import { createInterface } from 'node:readline';

// ─── Configuration ─────────────────────────────────────────────────────────────

const AGENT_RULE_NAMES = ['AGENTS.md', 'CLAUDE.md'];
const ROOT_AGENT_RULE = 'AGENTS.md';

const TEAM_DIRS = ['members', 'data', 'docs', 'archives'];

const TEAM_GITIGNORE = '.logs/\n';

const STUB_CONTENT = `<!-- Generated by teamos init. Do not edit — see teamos/agent-rules/cycle.md -->
Read and follow the TeamOS cycle rules in [teamos/agent-rules/cycle.md](../teamos/agent-rules/cycle.md).
`;

const DEFAULT_ORG = `# Organization

## Mission

[Define the team's mission here]

## Values

- [Value 1]
- [Value 2]

## Structure

[Describe team structure, reporting relationships, decision-making processes]

## Policies

### Communication
- Members communicate via inbox messages
- Urgent matters use priority: pressing
- Respond to messages within their priority timeframe

### Work Allocation
- Projects are assigned via projects.json
- Members track their own TODOs
- Cycle processing follows role category sequencing:
  1. Architects (design decisions first)
  2. Developers (implementation follows design)
  3. Reviewers (QA after implementation)
  4. Support (documentation, ops after review)
  5. Coordinators (management anytime)

### Quality Standards
[Define quality expectations]
`;

// ─── Helpers ───────────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const TEAMOS_ROOT = resolve(__dirname, '..');

function log(msg) { console.log(`  ${msg}`); }
function warn(msg) { console.warn(`  ! ${msg}`); }

async function exists(path) {
	try { await access(path, constants.F_OK); return true; } catch { return false; }
}

async function isSymlink(path) {
	try { const s = await lstat(path); return s.isSymbolicLink(); } catch { return false; }
}

async function isFile(path) {
	try { const s = await lstat(path); return s.isFile(); } catch { return false; }
}

async function readTextOrEmpty(path) {
	try { return await readFile(path, 'utf-8'); } catch { return ''; }
}

async function writeIfMissing(path, content, label) {
	if (await exists(path)) {
		log(`${label} already exists, skipping`);
		return false;
	}
	await writeFile(path, content, 'utf-8');
	log(`Created ${label}`);
	return true;
}

async function addGitignoreEntry(gitignorePath, entry) {
	const content = await readTextOrEmpty(gitignorePath);
	if (content.split('\n').some(line => line.trim() === entry.trim())) {
		return false;
	}
	const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
	await writeFile(gitignorePath, content + separator + entry + '\n', 'utf-8');
	return true;
}

async function promptYesNo(question, defaultNo = true) {
	const rl = createInterface({ input: process.stdin, output: process.stdout });
	const hint = defaultNo ? '[y/N]' : '[Y/n]';
	return new Promise((resolve) => {
		rl.question(`  ${question} ${hint} `, (answer) => {
			rl.close();
			const a = answer.trim().toLowerCase();
			if (a === '') resolve(!defaultNo);
			else resolve(a === 'y' || a === 'yes');
		});
	});
}

// ─── Detection ─────────────────────────────────────────────────────────────────

/**
 * Determine installation mode.
 * Returns { mode: 'submodule' | 'subtree' | 'symlink', needsRootSymlink: boolean }
 */
async function detectMode(projectRoot) {
	const teamosInProject = join(projectRoot, 'teamos');

	if (await exists(teamosInProject)) {
		if (await isSymlink(teamosInProject)) {
			log('Detected: teamos is a symlink');
			return { mode: 'symlink', needsRootSymlink: false };
		}

		const dotGitPath = join(teamosInProject, '.git');
		if (await isFile(dotGitPath)) {
			const content = await readTextOrEmpty(dotGitPath);
			if (content.includes('gitdir:')) {
				log('Detected: teamos is a git submodule');
				return { mode: 'submodule', needsRootSymlink: false };
			}
		}

		const gitmodulesContent = await readTextOrEmpty(join(projectRoot, '.gitmodules'));
		if (gitmodulesContent.includes('path = teamos') || gitmodulesContent.includes('path=teamos')) {
			log('Detected: teamos is a git submodule (not yet initialized)');
			return { mode: 'submodule', needsRootSymlink: false };
		}

		log('Detected: teamos is a git subtree (or plain directory)');
		return { mode: 'subtree', needsRootSymlink: false };
	}

	// teamos not in project — running from external path, symlink mode
	log('teamos not found in project — will create symlink');
	return { mode: 'symlink', needsRootSymlink: true };
}

// ─── Init steps ────────────────────────────────────────────────────────────────

async function createRootSymlink(projectRoot) {
	const target = relative(projectRoot, TEAMOS_ROOT);
	const linkPath = join(projectRoot, 'teamos');

	try {
		await symlink(target, linkPath, 'dir');
		log(`Created symlink: teamos -> ${target}`);
	} catch (err) {
		if (err.code === 'EPERM' || err.code === 'EACCES') {
			console.error('\nFailed to create symlink (permission denied).');
			console.error('On Windows, enable Developer Mode or run as administrator.');
			process.exit(1);
		}
		throw err;
	}
}

async function createTeamScaffold(projectRoot) {
	const teamDir = join(projectRoot, 'team');

	// Create directories
	for (const dir of TEAM_DIRS) {
		await mkdir(join(teamDir, dir), { recursive: true });
	}
	await mkdir(join(teamDir, '.logs'), { recursive: true });
	log('Ensured team/ directories');

	// Create workspace files
	await writeIfMissing(join(teamDir, 'org.md'), DEFAULT_ORG, 'team/org.md');
	await writeIfMissing(join(teamDir, 'members.json'), '{\n  "members": []\n}\n', 'team/members.json');
	await writeIfMissing(join(teamDir, 'memos.json'), '{\n  "items": []\n}\n', 'team/memos.json');
	await writeIfMissing(join(teamDir, 'projects.json'), '{\n  "projects": []\n}\n', 'team/projects.json');

	// Create .gitignore
	const gitignorePath = join(teamDir, '.gitignore');
	if (!await exists(gitignorePath)) {
		await writeFile(gitignorePath, TEAM_GITIGNORE, 'utf-8');
		log('Created team/.gitignore');
	} else {
		log('team/.gitignore already exists, skipping');
	}
}

async function createTeamStubs(projectRoot) {
	const teamDir = join(projectRoot, 'team');

	for (const name of AGENT_RULE_NAMES) {
		await writeIfMissing(
			join(teamDir, name),
			STUB_CONTENT,
			`team/${name}`,
		);
	}
}

async function createTeamSymlinks(projectRoot) {
	const teamDir = join(projectRoot, 'team');
	const target = join('..', 'teamos', 'agent-rules', 'cycle.md');

	for (const name of AGENT_RULE_NAMES) {
		const linkPath = join(teamDir, name);
		if (await exists(linkPath)) {
			log(`team/${name} already exists, skipping`);
			continue;
		}
		try {
			await symlink(target, linkPath, 'file');
			log(`Created symlink: team/${name} -> ${target}`);
		} catch (err) {
			if (err.code === 'EPERM' || err.code === 'EACCES') {
				warn(`Symlink failed for team/${name} — falling back to stub file`);
				await writeFile(linkPath, STUB_CONTENT, 'utf-8');
				log(`Created stub: team/${name} (symlink fallback)`);
			} else {
				throw err;
			}
		}
	}
}

async function ensureRootAgentRules(projectRoot) {
	const rootSection = await readFile(join(TEAMOS_ROOT, 'agent-rules', 'root.md'), 'utf-8');
	const name = ROOT_AGENT_RULE;
	const filePath = join(projectRoot, name);
	const existing = await readTextOrEmpty(filePath);

	if (existing.includes('## TeamOS')) {
		log(`${name} already has teamos section, skipping`);
		return;
	}

	const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : existing.length > 0 ? '\n' : '';
	await writeFile(filePath, existing + separator + rootSection, 'utf-8');
	log(existing.length > 0 ? `Appended teamos section to ${name}` : `Created ${name}`);
}

async function updateGitignoreForSymlinks(projectRoot) {
	const gitignorePath = join(projectRoot, '.gitignore');
	const entries = ['teamos', ...AGENT_RULE_NAMES.map(n => `team/${n}`)];

	let added = false;
	for (const entry of entries) {
		if (await addGitignoreEntry(gitignorePath, entry)) {
			added = true;
		}
	}
	if (added) {
		log('Updated .gitignore with teamos symlink entries');
	} else {
		log('.gitignore already has teamos entries, skipping');
	}
}

// ─── CLI ───────────────────────────────────────────────────────────────────────

function parseArgs(argv) {
	const opts = { projectRoot: process.cwd() };
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--project' && argv[i + 1]) {
			opts.projectRoot = resolve(argv[++i]);
		} else if (argv[i] === '--help') {
			console.log([
				'TeamOS project initialization',
				'',
				'Usage:',
				'  node teamos/scripts/init.mjs              # submodule or subtree mode',
				'  node /path/to/teamos/scripts/init.mjs     # symlink mode',
				'  node teamos/scripts/init.mjs --project /path/to/project',
				'',
				'Creates the team/ workspace scaffold and agent-rules references.',
				'Idempotent — safe to re-run at any time.',
			].join('\n'));
			process.exit(0);
		}
	}
	return opts;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
	const opts = parseArgs(process.argv.slice(2));
	const projectRoot = opts.projectRoot;

	console.log(`\nTeamOS init — project: ${projectRoot}`);
	console.log(`              teamos:  ${TEAMOS_ROOT}\n`);

	// Verify teamos has the expected structure
	const rulesFile = join(TEAMOS_ROOT, 'agent-rules', 'cycle.md');
	if (!await exists(rulesFile)) {
		console.error(`Cannot find ${rulesFile} — is this a valid teamos checkout?`);
		process.exit(1);
	}

	const { mode, needsRootSymlink } = await detectMode(projectRoot);

	// Step 1: Create root symlink if needed (symlink mode only)
	if (needsRootSymlink) {
		await createRootSymlink(projectRoot);
	}

	// Step 2: Create team/ scaffold
	await createTeamScaffold(projectRoot);

	// Step 3: Create agent-rule references in team/
	if (mode === 'submodule' || mode === 'subtree') {
		await createTeamStubs(projectRoot);
	} else {
		await createTeamSymlinks(projectRoot);
	}

	// Step 4: Ensure root AGENTS.md has teamos section
	await ensureRootAgentRules(projectRoot);

	// Step 5: Update .gitignore (symlink mode only)
	if (mode === 'symlink') {
		await updateGitignoreForSymlinks(projectRoot);
	}

	console.log('\nDone.\n');
}

main().catch((err) => {
	console.error('TeamOS init failed:', err);
	process.exit(1);
});
